blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/libra-trading/libra/discussions
    about: For questions and general discussion
  - name: Documentation
    url: https://github.com/libra-trading/libra/wiki
    about: Check the documentation before opening an issue
